[30.003309250] 2022-02-07 17:48:04,735 - INFO - launcher: Starting sanity checks
[31.000375748] 2022-02-07 17:48:04,736 - INFO - launcher: Checking for Python 3.5+
[31.000375748] 2022-02-07 17:48:04,736 - INFO - launcher: Checking console encoding
[31.000375748] 2022-02-07 17:48:04,736 - INFO - launcher: Setting console encoding to UTF-8
[32.003402710] 2022-02-07 17:48:04,737 - INFO - launcher: Ensuring we're in the right environment
[33.012866974] 2022-02-07 17:48:04,738 - INFO - launcher: Adding local bins/ folder to path
[508.670806885] 2022-02-07 17:48:05,214 - INFO - launcher: Required checks passed.
[509.643793106] 2022-02-07 17:48:05,215 - INFO - launcher: Optional checks passed.
[509.643793106] 2022-02-07 17:48:05,215 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1.2350430488586426] 2022-02-07 17:48:05,940 - WARNING - musicbot.config | In config.py, line 116 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[1.2350430488586426] 2022-02-07 17:48:05,940 - INFO - musicbot.config | In config.py, line 127 in run_checks: Using i18n: config/i18n/en.json
[1.2360436916351318] 2022-02-07 17:48:05,941 - DEBUG - musicbot.bot | In bot.py, line 220 in _setup_logging: Set logging level to INFO
[1.2381496429443359] 2022-02-07 17:48:05,943 - DEBUG - musicbot.json_file | In json_file.py, line 8 in __init__: Init JSON obj with config/i18n/en.json
[1.2750451564788818] 2022-02-07 17:48:05,980 - INFO - musicbot.bot | In bot.py, line 91 in __init__: Starting MusicBot 766659b
[1.4058940410614014] 2022-02-07 17:48:06,111 - DEBUG - musicbot.spotify | In spotify.py, line 74 in get_token: Created a new access token: {'access_token': 'BQAsfSQULrArk5lCqt3ew-nJBT5ubra4NvNnRQiS9tHL4G0DugQ985-cM07PHLiPK8DXZXQfXxE5OscbYAI', 'token_type': 'Bearer', 'expires_in': 3600, 'expires_at': 1644288486}
[1.4069476127624512] 2022-02-07 17:48:06,112 - INFO - musicbot.bot | In bot.py, line 116 in __init__: Authenticated with Spotify successfully using client ID and secret.
[3.9588422775268555] 2022-02-07 17:48:08,664 - DEBUG - musicbot.bot | In bot.py, line 839 in on_ready: Connection established, ready to go.
[3.9588422775268555] 2022-02-07 17:48:08,664 - DEBUG - musicbot.bot | In bot.py, line 331 in _cache_app_info: Caching app info
[4.0916929244995117] 2022-02-07 17:48:08,797 - DEBUG - musicbot.bot | In bot.py, line 665 in _scheck_ensure_env: Ensuring data folders exist
[4.0926609039306641] 2022-02-07 17:48:08,798 - DEBUG - musicbot.bot | In bot.py, line 681 in _scheck_server_permissions: Checking server permissions
[4.0926609039306641] 2022-02-07 17:48:08,798 - DEBUG - musicbot.bot | In bot.py, line 685 in _scheck_configs: Validating config
[4.0926609039306641] 2022-02-07 17:48:08,798 - DEBUG - musicbot.config | In config.py, line 227 in async_validate: Validating options...
[4.0926609039306641] 2022-02-07 17:48:08,798 - DEBUG - musicbot.config | In config.py, line 241 in async_validate: Acquired owner id via API
[4.0926609039306641] 2022-02-07 17:48:08,798 - DEBUG - musicbot.bot | In bot.py, line 688 in _scheck_configs: Validating permissions config
[4.0926609039306641] 2022-02-07 17:48:08,798 - DEBUG - musicbot.permissions | In permissions.py, line 94 in async_validate: Validating permissions...
[4.0926609039306641] 2022-02-07 17:48:08,798 - DEBUG - musicbot.permissions | In permissions.py, line 98 in async_validate: Fixing automatic owner group
[4.0926609039306641] 2022-02-07 17:48:08,798 - INFO - musicbot.bot | In bot.py, line 856 in on_ready: Connected: 940412327751200788/试做机1号·改#2297
[4.1051726341247559] 2022-02-07 17:48:08,810 - WARNING - musicbot.bot | In bot.py, line 884 in on_ready: Owner could not be found on any guild (id: 287488743361871872)

[4.1061830520629883] 2022-02-07 17:48:08,811 - INFO - musicbot.bot | In bot.py, line 886 in on_ready: Guild List:
[4.1061830520629883] 2022-02-07 17:48:08,811 - INFO - musicbot.bot | In bot.py, line 889 in on_ready:  - XYZ
[4.1071848869323730] 2022-02-07 17:48:08,812 - INFO - musicbot.bot | In bot.py, line 927 in on_ready: Not bound to any text channels
[4.1080837249755859] 2022-02-07 17:48:08,813 - INFO - musicbot.bot | In bot.py, line 953 in on_ready: Not autojoining any voice channels
[71.1945548057556152] 2022-02-07 17:49:15,899 - INFO - musicbot.bot | In bot.py, line 2575 in on_message: 287488743361871872/COl0rBee#8715: **summon
[71.6742486953735352] 2022-02-07 17:49:16,379 - INFO - musicbot.bot | In bot.py, line 1813 in cmd_summon: Joining XYZ/星际
[71.6772572994232178] 2022-02-07 17:49:16,382 - DEBUG - musicbot.bot | In bot.py, line 492 in on_player_stop: Running on_player_stop
[81.9105186462402344] 2022-02-07 17:49:26,615 - INFO - musicbot.bot | In bot.py, line 2575 in on_message: 287488743361871872/COl0rBee#8715: **disconnect
